#! /bin/bash -ex

# Script to build the kernel

TOP=`dirname $0`

[ $TOP = "." ] && TOP=`pwd`

source $TOP/bldconfig

lxdir=$TOP/external/linux-$KERVERSION

. $TOP/dl-kernel

cp kernel-config $lxdir/.config

(
	cd $lxdir
	make -j 6
)
