#! /bin/bash -ex

# Script to build the initial ramdisk

TOP=`dirname $0`

[ $TOP = "." ] && TOP=`pwd`

source $TOP/bldconfig

brdir=$TOP/external/buildroot-$BRVERSION

cp /etc/localtime $TOP/extrafiles/etc
cp /etc/timezone $TOP/extrafiles/etc

(
	cd $brdir
	[ ! -z "$1" ] && make clean
	make
) && $TOP/build-kernel

