#! /bin/bash

TOP=`dirname $0`

[ $TOP = "." ] && TOP=`pwd`

hash=`echo $TOP | cksum | cut -d' ' -f 1`

export WDIR=$HOME/.vmalwc/$hash

mkdir -p $WDIR

[ -z "$2" ] && {
	echo Usage: `basename $0` from script [size] [to]
	echo "Download or unpack 'from', run 'script', use volume of 'size', save volume to 'to'"
	exit 1
}

from="$1"
vsize="${3:-1G}"

sysin="$2"

if [ ! -z "$4" ] ; then
	tolib="-lib tolib -path `dirname $4` -type 9p -rw"
else
	tolib=""
fi

case "$from" in
		http://*|https://*)
			fromlib=""
			gcmd="wget $from -O - "
		;;
		*)
			fromlib="-lib fromlib -path `dirname $1` -type 9p -ro"
			gcmd="cat $from "
esac

source $TOP/bldconfig

KERNEL=${KERNEL:-$TOP/external/linux-$KERVERSION/arch/x86_64/boot/bzImage}
KVM=${KVM:-$TOP/external/qemu-$QEMUVERSION/x86_64-softmmu/qemu-system-x86_64}

$TOP/bin/fghc -mem 256M -kernel $KERNEL -kvm  $KVM -workdir $WDIR \
    -step fmtvol \
		-lib vol0 -new $vsize -rw -type qcow2 \
		-exec 'mkfs.ext2 /dev/vda' \
	-step unpack \
		-lib @fmtvol.vol0 $fromlib \
		-exec "$gcmd | tar xz -C /volumes/vda" \
	-step makeimage -after unpack \
		-lib @fmtvol.vol0 -rw \
		-lib inlib -path `dirname $sysin` -type 9p -ro \
		-exec 'mchroot /volumes/vda bash /proc/self/fd/3' \
		-sysin /host/inlib/`basename $sysin` | make -f - &

#tail --pid $! -q -F $sysout 2>/dev/null
