#! /bin/bash -ex

# stolen from the original coreos run script.

find_ssh_keys() {
    if [ -S "$SSH_AUTH_SOCK" ]; then
        ssh-add -L
    fi
    for default_key in ~/.ssh/id_*.pub; do
        if [ ! -f "$default_key" ]; then
            continue
        fi
        cat "$default_key"
    done
}

write_ssh_keys() {
    echo "#cloud-config"
    echo "ssh_authorized_keys:"
    sed -e 's/^/ - /'
}

CONFIG_DRIVE=$(mktemp -t -d loadcore-configdrive.XXXXXXXXXX)
if [ $? -ne 0 ] || [ ! -d "$CONFIG_DRIVE" ]; then
    echo "$0: mktemp -d failed!" >&2
    exit 1
fi
trap "rm -rf '$CONFIG_DRIVE'" EXIT
mkdir -p "${CONFIG_DRIVE}/openstack/latest"

# Copy the host local time file to the config drive

cp -H /etc/localtime "${CONFIG_DRIVE}/host-localtime"

TOP=`dirname $0`

[ $TOP = "." ] && TOP=`pwd`

WDIR=${WDIR:-/tmp}

source $TOP/bldconfig

KERNEL=${KERNEL:-$TOP/external/linux-$KERVERSION/arch/x86_64/boot/bzImage}
KVM=${KVM:-$TOP/external/qemu-$QEMUVERSION/x86_64-softmmu/qemu-system-x86_64}
XDISPLAY=`echo $DISPLAY | tr -d ':' | cut -d. -f 1`

# Obtain the coreos version number for shell prompt from the cromeos' own load script

COREDIR=$TOP/external/coreos

if [ -r $COREDIR/coreos_production_qemu.sh ] ; then
	name=$(grep "^VM_NAME" $COREDIR/coreos_production_qemu.sh | head -n 1 | cut -d"=" -f 2 | tr -d \'\")
fi

name=${name:-loadcore}

# Find the pulseaudio server listening address if any

eval `pax11publish -i`

if [ -z "$PULSE_SERVER" ] ; then
        export PULSE_SERVER=unix:`pactl info|grep "^Server String:"|cut -d":" -f 2|tr -d ' '`
fi

# If does not exist, create a btrfs volume of 1/4 space available for the work area path

IMGSTOR="$WDIR/imagestore"

if [ ! -f $IMGSTOR ] ; then
	df=`df --output=avail $WDIR | tail -n 1`
	imsz=$(($df/4))
	fallocate -l ${imsz}K $IMGSTOR
	mkfs.btrfs $IMGSTOR
fi

# Extract the SSH public key for the current user

sshkey=$(find_ssh_keys)

# Copy current user information to the coreos environment.

(
	echo USER=$USER
	echo HOME=$HOME
) > $CONFIG_DRIVE/user_environment

# Create an user for coreos with the same name as the current user, enable public key login.
# Add a number of systemd units to run at start.

( 
cat <<EOF
#cloud-config
users:
  - name: $USER
    homedir: $HOME
    groups:
      - wheel
      - docker
      - systemd-journal
      - portage
      - core
      - sudo
    ssh-authorized-keys:
      - $sshkey
coreos:
  units:
    - name: copy-host-files.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStartPre=/bin/cp /media/configvirtfs/host-localtime /etc/localtime
        ExecStartPre=/bin/mkdir -p /etc/vmalwc/
        ExecStartPre=/bin/cp /media/configvirtfs/user_info /etc/vmalwc/environment
        ExecStartPre=/bin/cp /media/configvirtfs/user_environment /etc/vmalwc/user_environment
        ExecStartPre=/bin/sh -c "echo NUID=`id -u $USER` >> /etc/vmalwc/user_environment"
        ExecStart=/bin/true
    - name: remove-default-user.service
      command: start
      content: |
        [Service]
        Type=oneshot
        ExecStart=/sbin/userdel core
    - name: var-lib-machines.mount
      command: start
      content: |
        [Mount]
        What=/dev/vdb
        Where=/var/lib/machines
        Type=btrfs
EOF
) >> $CONFIG_DRIVE/openstack/latest/user_data

# For any file specified on the command line, treat it as a systemd unit and try
# to add to the cloud config file. Use the X-cloud-config-command line to form the command parameter.

(
	for s in "$@" ; do
		if [ ! -r $s ] ; then
			continue
		fi
		ucmd=$(grep "X-cloud-config-command=" $s | cut -d= -f 2)
		indent="    "
		echo "${indent}- name: $(basename $s)"
		if [ ! -z "$ucmd" ] ; then
			echo "${indent}  command: $ucmd"
		fi
		echo "${indent}  content: |"
		cat $s | sed "s/^/${indent}    /g"
done
) >> $CONFIG_DRIVE/openstack/latest/user_data


$TOP/bin/fghc -id $$-loadcore -mem 1G -kvm  $KVM -workdir $WDIR -video -audio -xdisplay $XDISPLAY \
	-hostname $name \
	-step loadcore -host -lbrst -xkernel $KERNEL -fwd 2222:22 -info $CONFIG_DRIVE/user_info \
		       -lib conf -path $CONFIG_DRIVE -ro -tag config-2 \
		       -lib core -path $COREDIR/coreos_production_qemu_image.img -snap -rw \
		       -lib imgstor -path $IMGSTOR -rw \
	-make &



FONT=${FONT:-terminus-18}

ssh-keyscan -v -p 2222 -T 20 -t dsa,ecdsa,ed25519 localhost

sleep 1

cd $WDIR

vmon=`find . -name "$$-loadcore*.monitor" || exit 0`

xterm -fn $FONT -fg lightgreen -bg black -title "$name: Console [$$]" -fullscreen \
	-e ssh -q -o StrictHostKeyChecking=no -p 2222 localhost && \
	(echo quit | socat stdio "unix-connect:$vmon")

