#! /bin/bash -ex

TOP=`dirname $0`

[ $TOP = "." ] && TOP=`pwd`

WDIR=${WDIR:-/tmp}

source $TOP/bldconfig

KERNEL=${KERNEL:-$TOP/external/linux-$KERVERSION/arch/x86_64/boot/bzImage}
KVM=${KVM:-$TOP/external/qemu-$QEMUVERSION/x86_64-softmmu/qemu-system-x86_64}
XDISPLAY=`echo $DISPLAY | tr -d ':' | cut -d. -f 1`

$TOP/bin/fghc -id $$-loadbase -mem 256M -kernel $KERNEL -kvm  $KVM -workdir $WDIR -video -xdisplay $XDISPLAY \
	-step loadbase -host -lbrst -lib image -path $TOP/image -ro \
				    -lib sysin -path $TOP/sysin -rw \
	-make &

FONT=${FONT:-terminus-18}

sleep 2

cd $WDIR

vcons=`find . -name $$-loadbase*vcons1 || exit 0`
vmon=`find . -name $$-loadbase*monitor || exit 0`

xterm -fn $FONT -fg lightgreen -bg black -title "$$-loadbase: Console" \
	-e socat 'stdio,raw,echo=0' "unix-connect:$vcons" && \
	(echo quit | socat stdio "unix-connect:$vmon")

