#! /bin/bash

# The startup script for VMALWC

sleep 0.25

TOP=`dirname $0`

if [ $TOP = "." ] ; then
	TOP=`pwd`
fi

killall -9 pulseaudio
pactl info >/dev/null

[ `ps aux | grep patunnel | wc -l` = 0 ] && $HOME/bin/patunnel 2>&1 >/dev/null &

PTPID=$!

cd $TOP

eval `pax11publish -i`

if [ -z "$PULSE_SERVER" ] ; then
	export PULSE_SERVER=unix:`pactl info|grep "^Server String:"|cut -d":" -f 2|tr -d ' '`
fi

xsetroot -solid darkgray

hash=`echo $TOP | cksum | cut -d' ' -f 1`

export WDIR=$HOME/.vmalwc/$hash

mkdir -p $WDIR

for p in $(cat $WDIR/*.pid) ; do
	kill $p
done

# If there is no window manager running then start core with extra units
# that may contain window manager as well, otherwise just start core itself.
# Pass all possible arguments from command line to loadcore

if (wmctrl -m 2>&1 >/dev/null) ; then

	./loadcore "$@"

else
	./loadcore  units/* "$@"
fi

kill -9 $PTPID

