#! /bin/sh
#
# Set hostname from the kernel command line
#

case "$1" in
	start)
		if [ ! -z "$hostname" ] ; then
			echo $hostname >/etc/hostname
			/bin/hostname -F /etc/hostname
		fi
		;;
	stop)
		;;
	*)
		echo "Usage $0 {start|stop}"
		exit 1
esac
