#! /bin/sh
#
# Find all 9p mount tags and mount them under /host
#

case "$1" in
	start)
		find /sys/devices -name mount_tag | while read ; do
			tag=`cat $REPLY`
			case "$tag" in
				H\#*)
					mtag=`echo -n "$tag" | sed 's/^H#//g'`
					base=$homebase
				;;
				*)
					mtag="$tag"
					base=/host
			esac
			mkdir -p $base/$mtag
			mount -t 9p $tag $base/$mtag
		done
		;;
	stop)
		find /sys/devices -name mount_tag | while read ; do
			tag=`cat $REPLY`
			umount /host/$tag
		done
		;;
	*)
		echo "Usage $0 {start|stop}"
		exit 1
esac
