#! /bin/bash -ex

# This script is to be invoked by apcon@.service before the application starts.
# The only parameter accepted is instance (unescaped). The script should mount all
# necessary filesystems inside the container.
# The instance name is expected in the format "container/executable/path arg arg arg".
# Only the first element before the first slash is of interest.

([ -z "$1" ] || [ -z "$HOME" ] || [ -z "$USER" ]) && {
	echo "No instance or home directory or username provided"
	exit 1
}

cont=$(echo "$1" | cut -d/ -f 1)

snapid=`echo "$1" | md5sum - | cut -d" " -f 1`

sncont="@${cont}.${snapid}"

btrfs sub snaps /var/lib/machines/$cont /var/lib/machines/$sncont

/bin/mount -t proc proc /var/lib/machines/$sncont/proc
/bin/mount --bind /dev /var/lib/machines/$sncont/dev
/bin/mount -t devpts devpts /var/lib/machines/$sncont/dev/pts
/bin/mount -t tmpfs tmpfs /var/lib/machines/$sncont/dev/shm
if [ -d /mnt/host/persistent_home/$cont ] && [ -w /mnt/host/persistent_home/$cont ] ; then
	/bin/mount --bind /mnt/host/persistent_home/$cont /var/lib/machines/$sncont/$HOME
else
	/bin/mkdir -p /var/lib/machines/$sncont/$HOME $HOME/$cont
	/bin/chown $USER /var/lib/machines/$sncont/$HOME $HOME/$cont
	/bin/mount --bind $HOME/$cont /var/lib/machines/$sncont/$HOME
fi
/bin/mkdir -p /var/lib/machines/$sncont/usr/share/applications
/bin/mkdir -p /var/vmalwc /var/lib/machines/$sncont/usr/share/vmalwc
/bin/mount --bind -r /var/vmalwc /var/lib/machines/$sncont/usr/share/vmalwc
/bin/mount --bind -r /var/vmalwc/allapps/desktop /var/lib/machines/$sncont/usr/share/applications
/bin/mkdir -p /var/vmalwc/boxes/$cont/inbox
/bin/chown $USER /var/vmalwc/boxes/$cont/inbox
/bin/mkdir -p /var/lib/machines/$sncont/var/vmalwc/inbox
/bin/mount --bind /var/vmalwc/boxes/$cont/inbox /var/lib/machines/$sncont/var/vmalwc/inbox
/bin/mkdir -p /var/lib/machines/$sncont/opt/vmalwc/bin
/bin/mount --bind -r /opt/vmalwc/client /var/lib/machines/$sncont/opt/vmalwc/bin
/bin/mkdir -p /var/lib/machines/$sncont/var/run/dbus /var/lib/machines/$sncont/run/dbus
/bin/mount --bind -r /var/run/dbus /var/lib/machines/$sncont/var/run/dbus
/bin/mount --bind -r /var/run/dbus /var/lib/machines/$sncont/run/dbus
/usr/bin/systemctl start job-inbox@$cont.path
for f in /etc/resolv.conf /etc/passwd /etc/group /etc/localtime ; do
	/usr/bin/touch /var/lib/machines/$sncont/$f
	/bin/mount --bind $f /var/lib/machines/$sncont/$f
done

