#! /bin/sh -ex

# Script to do a simple chroot into the given path, pre-mounting
# certain mountpoints into the chroot first and copying some files over.

# If import of the host user was specified in the kernel command line
# attempt to create the used in the chroot and then chroot to the
# target program as the host user. Programs like adduser and addgroup
# are expected in the chroot.

[ -z "$2" ] && {
	echo Usage `basename $0` root command
	exit 1
}

[ -z "$user" ] && homebase=""

for b in /dev /dev/pts /sys /proc /host $homebase \
	/var/run/avahi-daemon /run/avahi-daemon \
	/var/run/dbus /run/dbus ; do
	[ -d $b ] && { 
		mkdir -p $1/$b
		mountpoint -q $1/$b || mount -o rbind $b $1/$b
	}
done

for f in /etc/resolv.conf /etc/localtime /etc/timezone ; do
	[ -f $f ] && {
		mkdir -p $1/`dirname $f`
		cp $f $1/$f
	}
done

nr=$1

shift

if [ -z "$user" ] || [ -z "$gid" ] || [ -z "$uid" ]  ; then
	exec chroot $nr "$@"
else
	( chroot $nr addgroup --gid $gid $user || true ) &&
	echo Y | chroot $nr adduser --uid $uid --gid $gid \
			--home $homebase --disabled-login $user &&
	HOME=$homebase exec dbus-run-session chroot --userspec $uid:$gid $nr "$@"
fi

