#! /bin/sh

if [ -z "$2" ] ; then
	echo "Usage: $0 image command [args]"
	exit 1
fi

img=$1

shift

fcmd=$1

jobidx=${prefix:-job}

jobctl -mem 1G -audio -video -xdisplay $hostdisplay -id $jobidx \
	-step "$fcmd" -lib vol -path $img -snap -rw -user -make -quiet \
		-exec \"mchroot\ /volumes/vda\ `echo $@ | sed 's/ /\\ /g'`\"


